# Generated by Django 2.0.6 on 2018-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_backgroundtaskmodel_literalsettings_measuredataview_numericsettigs'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='BackgroundTaskModel',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('task_params', models.TextField()),
        #         ('task_hash', models.CharField(max_length=40)),
        #         ('repeat', models.BigIntegerField()),
        #         ('repeat_until', models.DateTimeField()),
        #         ('task_name', models.CharField(max_length=190)),
        #     ],
        #     options={
        #         'db_table': 'background_task',
        #         'managed': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='MeasureDataView',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('elapsed_time', models.IntegerField()),
        #         ('data', models.FloatField()),
        #         ('utimestamp', models.DateTimeField()),
        #     ],
        #     options={
        #         'db_table': 'fullmeasure',
        #         'managed': False,
        #     },
        # ),
        migrations.AlterModelOptions(
            name='aqinowcasthistory',
            options={'verbose_name': 'ICA de hora', 'verbose_name_plural': 'Historial ICA'},
        ),
        migrations.AlterModelOptions(
            name='aqirange',
            options={'verbose_name': 'Rango de calidad de Aire', 'verbose_name_plural': 'Rangos de calidad de Aire'},
        ),
        migrations.AlterModelOptions(
            name='concentrations',
            options={'verbose_name': 'Concentracion horaria', 'verbose_name_plural': 'Concentraciones horarias'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Pregunta Frecuente', 'verbose_name_plural': 'Preguntas frecuentes'},
        ),
        migrations.AlterModelOptions(
            name='literalsettings',
            options={'verbose_name': 'Configuracion literal', 'verbose_name_plural': 'Configuraciones literales'},
        ),
        migrations.AlterModelOptions(
            name='measuredata',
            options={'verbose_name': 'Concentracion 300 segundos', 'verbose_name_plural': 'Concentraciones 300 segundos'},
        ),
        migrations.AlterModelOptions(
            name='numericsettigs',
            options={'verbose_name': 'Configuracion numerica', 'verbose_name_plural': 'Configuraciones numericas'},
        ),
        migrations.AddField(
            model_name='measuredata',
            name='alarm',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measuredata',
            name='error',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
