# Generated by Django 2.0.6 on 2018-07-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180723_1516'),
    ]

    operations = [
    
    ]
