# Generated by Django 2.0.6 on 2018-07-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_backgroundtaskmodel_measuredataview'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='BackgroundTaskModel',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('task_params', models.TextField()),
        #         ('task_hash', models.CharField(max_length=40)),
        #         ('repeat', models.BigIntegerField()),
        #         ('repeat_until', models.DateTimeField()),
        #         ('task_name', models.CharField(max_length=190)),
        #     ],
        #     options={
        #         'db_table': 'background_task',
        #         'managed': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='MeasureDataView',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('elapsed_time', models.IntegerField()),
        #         ('data', models.FloatField()),
        #         ('utimestamp', models.DateTimeField()),
        #     ],
        #     options={
        #         'db_table': 'fullmeasure',
        #         'managed': False,
        #     },
        # ),
        migrations.CreateModel(
            name='AQINowCastHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AQIRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clow', models.FloatField()),
                ('chigh', models.FloatField()),
                ('ilow', models.FloatField()),
                ('ihigh', models.FloatField()),
                ('category', models.CharField(max_length=250)),
                ('category_descriptor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('publish', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
