# Generated by Django 2.0.6 on 2018-07-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180726_1543'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='BackgroundTaskModel',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('task_params', models.TextField()),
        #         ('task_hash', models.CharField(max_length=40)),
        #         ('repeat', models.BigIntegerField()),
        #         ('repeat_until', models.DateTimeField()),
        #         ('task_name', models.CharField(max_length=190)),
        #     ],
        #     options={
        #         'db_table': 'background_task',
        #         'managed': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='MeasureDataView',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('elapsed_time', models.IntegerField()),
        #         ('data', models.FloatField()),
        #         ('utimestamp', models.DateTimeField()),
        #     ],
        #     options={
        #         'db_table': 'fullmeasure',
        #         'managed': False,
        #     },
        # ),
        migrations.CreateModel(
            name='LiteralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NumericSettigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
        ),
    ]
