# Generated by Django 2.0.6 on 2018-08-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180801_1444'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='BackgroundTaskModel',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('task_params', models.TextField()),
        #         ('task_hash', models.CharField(max_length=40)),
        #         ('repeat', models.BigIntegerField()),
        #         ('repeat_until', models.DateTimeField()),
        #         ('task_name', models.CharField(max_length=190)),
        #     ],
        #     options={
        #         'managed': False,
        #         'db_table': 'background_task',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='MeasureDataView',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('elapsed_time', models.IntegerField()),
        #         ('data', models.FloatField()),
        #         ('utimestamp', models.DateTimeField()),
        #     ],
        #     options={
        #         'managed': False,
        #         'db_table': 'fullmeasure',
        #     },
        # ),
        migrations.AlterField(
            model_name='measuredata',
            name='alarm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='measuredata',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
