# Generated by Django 2.0.6 on 2018-07-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_history'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='measurements',
            name='current_timestamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
