# Generated by Django 2.0.6 on 2018-07-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180702_1721'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='measurements',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='start_time',
        ),
        migrations.AddField(
            model_name='measurements',
            name='start_timestamp',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
