# Generated by Django 2.0.6 on 2018-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180702_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_start', models.DateTimeField()),
                ('start', models.DateTimeField()),
                ('final', models.DateTimeField()),
                ('sum', models.FloatField()),
                ('count', models.IntegerField()),
            ],
        ),
    
    ]
